### ISSUE TITLE
 [ERROR] Could not pass event PlayerMoveEvent to JukeAlert v1.3.1

### ISSUE THREAD

**Issue by ttk2** [Civcraft/JukeAlert#21] opened 2015-03-29 23:54 UTC
2015-03-29 19:58:45 [ERROR] Could not pass event PlayerMoveEvent to JukeAlert v1.3.1
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:249) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.PacketPlayInFlying.a(SourceFile:137) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.PacketPlayInPositionLook.handle(SourceFile:20) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:184) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
Caused by: java.lang.NullPointerException
        at com.untamedears.JukeAlert.util.OnlineGroupMembers.getNextMember(OnlineGroupMembers.java:179) ~[?:?]
        at com.untamedears.JukeAlert.util.OnlineGroupMembers.getPlayerByState(OnlineGroupMembers.java:201) ~[?:?]
        at com.untamedears.JukeAlert.util.OnlineGroupMembers.getNextPlayer(OnlineGroupMembers.java:247) ~[?:?]
        at com.untamedears.JukeAlert.util.OnlineGroupMembers.startIterating(OnlineGroupMembers.java:130) ~[?:?]
        at com.untamedears.JukeAlert.util.OnlineGroupMembers.iterator(OnlineGroupMembers.java:123) ~[?:?]
        at com.untamedears.JukeAlert.util.Utility.notifyGroup(Utility.java:70) ~[?:?]
        at com.untamedears.JukeAlert.listener.JukeAlertListener.enterSnitchProximity(JukeAlertListener.java:363) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor49.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_75]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_75]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        ... 13 more

**Comment by ttk2** [comment] 2015-04-01 01:50
this is still occuring.

**Comment by Pentom** [comment] 2015-04-10 03:51
This appears to be the same issue that I looked at briefly back in november?

Back then, I reproduced the issue due to what appears to be a data consistency issue between two tables.  Did we ever run the sql queries I mentioned to see where the data issue was?

https://github.com/Civcraft/JukeAlert/issues/5#issuecomment-63567962

**Comment by erocs** [comment] 2015-04-10 04:29
I probably missed your response. So these are likely instances of those deleted cheap educational accounts.

I will delete all occurrences of a missing UUID from faction_member and reassign all of these instances of unknown group founders to my UUID.

**Comment by Pentom** [comment] 2015-04-12 01:02
Issue stop occurring after you made these changes?

**Comment by ttk2** [comment] 2015-04-12 02:33
looks like we still get some.

**Comment by Pentom** [comment] 2015-04-12 11:30
Interesting.  Erocs - have the changes I mentioned been made then and we are still getting errors?  Don't know if its still occurring because it was an incomplete fix or because it hadn't been changed yet.

**Comment by erocs** [comment] 2015-04-12 22:02
I wasn't in a position to do the work the other night. These old deleted
educational accounts should now be purged from the NameLayer tables.

**Comment by JosephDonaldson** [comment] 2015-04-14 00:09
TTK2 - How we looking for these alerts at this time?

**Comment by ttk2** [comment] 2015-04-14 02:14
not many if any.

**Closed** 2015-04-24 16:49 UTC
Labels: bug, P1 - Critical
